apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: kubeseal
  labels:
    argocd.argoproj.io/managed-by=openshift-gitops
spec:
  project: cluster-config
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.2.0
    helm:
      releaseName: sealed-secrets
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubeseal
  syncPolicy:
    syncOptions:
      - CreateNamespace=true