apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-config
  namespace: argocd
spec:
  encryptedData:
    alertmanager.yaml: AgCXHbUS69eFGlA1Mhtcdp0weEx+PFPQh48CUoO5jdidzQ5x+FBU4uPLt4k72+kF3JSSMaT4X9X01aLJUtDFw43ai+s36q2/z4dLHxa9+PJ0+FPdgeNojjcqbw/8ZbxNrywpGZlp+BjTymy9GZ0C5UyOdbuxHmvH2F4DNXKslWJ0RfX2pvXgINlLl6wbXvk4lpP8nXZWs/RuyKb1zsuwJzSEPXVoN7ErF8KXibQ/0YhCIAXRtyI6ODmt7iru8nU7b3ryW8xlymXmPGm4/rgLEEpqR237RMNl8FppF5SOYf8TUHwl84bmD0ulUz8RsD8ufWRteEhSTZr+IBGVGq6wCoG605+9AfE79buZHvti6phVhb0IP7SP/bTylpfjKnbTDIL5UPjB3qnf8QpwhNSAaJX24HaBkqRgixRz9iRnbaC0vWbr2QRbETYf7P3OxHXLX1BBsxb6FYpnqcPamX2uac0Oln5TdehojgMTRS+Wde9oZx+D5dhJqHFBoExCQqpV9aCxPyLWJgCQwT1Ucprep3SU3RgBsCdeq39Iu0wOgGQIy/lpAXhSlvCC570ll90T84yAHfngFIljSteVhAXJ0pSGjluZwv8/FsHfJpFpOvDqJDUzEmygiOaqR7cZDLySVRyEdOqZyuhMH8QHnNejHwV9TsNtBQBEy6TKYdsz9Hd3qi3Lq1VektOHAduAaTCU6Sc7QGUaRhkrA/RKUlR6Syrt34C47uZESFXriKsH+TSLsnQYeEV7SIK5jwOajl8lhY6SW8htz67n39Ao4BpjGs14avToC0SgseLOGk98h2lJFHag+s9S76PGAEHXsJFbG8u0Xy5OCspz/1+Yz7SmS5zf45BQxgwCmYENvDGTOC7W2Sgyo2KD6VfiLlnx9Ckh9SwNKDy/xani28MewAogosB4nPhesDjEpH6tgmr5Fw7TdwBZTzxUCtVlmgG6bD+0v1glo5tJCREq/X4ocaZxbd+l1RxWexvIJt1YARah/ffeZmcq73CTrf6HFLJKP44YqD1Dj7BD9utLh1kZZPeasIwAqZtEgpJ5btFGGrhmuGlzQreUZwGXbZ43S65LmuFVnep6uyLzXZzd/Ok4LlQP13CxCQvPhpZ5hrW70MEHKv6RF03rHWCp9iALsjsB/ieqzMasweSegrAL5iVc+HmmxpGoAK/DnDMQtkw9b8LXqdic2CV+3+qncnKSyLE9l6/Tt6PQFaTJaJs93YBbmUF1Qew86oFrs6qXFiLTWojTlqGQKjSN2aVvh29dxNQGf61rpsx1hpyzVe2I0cP5W39ICnbdYBc5JRF77iSSNUwbBeqrD9oJ+ef+xPUzzbCKvPdaIkspvbhCDAI1lpQW40sWxDcWagjT3tUUHt53VztasJIWOqpnFXFAWIIntHH2TF2sb2b8ue5/1WdpwAZd+3dNQ53wfgcPpOlSwkFIUQp8L/lSXTHOu3GwFCdkj/Uz0LhkxcTOiGdFcCy2lmqxjjz4oEUO1WNToLREds/D6I+gYzmZ0nySjikavvxcVfUUXozvrY0QtA+LkEby6voOxoC1qgBtDcN/6AQfmVRuznYHFmE4ZsEfRHxB/wVVgqwRSTYNqOEc3VPUxsNonpi9z7fmtrcGDR2AaA62EXkt5O7VYLTvmmqnNZrUHz9gln4N
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: alertmanager-config
      namespace: argocd
    type: Opaque

