apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vplugin-secret
  namespace: openshift-gitops
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: "jarvis-test"
    notifications.argoproj.io/subscribe.on-sync-failed.slack: "jarvis-test"
spec:
  destination:
    namespace: openshift-gitops 
    server: 'https://kubernetes.default.svc'         
  project: gitops-config
  source:
    repoURL: 'https://github.com/StinkyBenji/openshift-gitops-practice'
    path: argocd/apps/argocd-vault
    targetRevision: master
    plugin:
      name: argocd-vault-plugin
      env:
        - name: AVP_K8S_ROLE
          value: vplugin
        - name: AVP_TYPE
          value: vault
        - name: AVP_VAULT_ADDR
          value: 'http://vault.openshift-gitops.svc.cluster.local:8200'
        - name: AVP_AUTH_TYPE
          value: k8s
