apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calert
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: manifest/argocd/apps/calert/base/apps
    repoURL: https://github.com/StinkyBenji/hands-on-openshift-gitops
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
