apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base
  
patchesJson6902:
  - target:
      kind: Secret
      name: argocd-notifications-secret
      version: v1
    path: patch-slack-secret.yaml