- op: add
  path: /spec/source/helm
  value:
    values: |
      nameOverride: custom-argo
      redis:  
        containerSecurityContext:
          runAsUser:
          fsGroup:
      repoServer:
        volumeMounts:
          - name: helm-values
            mountPath: /helm-values
        volumes:
          - name: helm-values
            secret:
              secretName: helm-values
      server:  
        route:
          enabled: true     