- op: add
  path: /spec/source/helm
  value:
    values: |
      nameOverride: custom-argo
      redis:  
        containerSecurityContext:
          runAsUser: 1000660000
          fsGroup: 1000660000
      repoServer:
        volumeMounts:
          - name: helm-values
            mountPath: /helm-values
        volumes:
          - name: helm-values
            secret:
              secretName: helm-values
      openshift:
        enabled: true
      server:  
        route:
          enabled: true     