- op: add
  path: /spec/source/helm
  value:
    values: |
      nameOverride: custom-argo
      global:
        securityContext:
          runAsUser:
          fsGroup:
          runAsGroup:
      repoServer:
        volumeMounts:
          - name: helm-values
            mountPath: /helm-values
        volumes:
          - name: helm-values
            secret:
              secretName: helm-values
      route:
        enabled: true     