apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: helm-values
  namespace: argocd
spec:
  encryptedData:
    calert-helm.yaml: AgA6td1SFTHlJJyFuGQ71H91GnjmVCl6jLC+N4nsMl1k4xI/xl+tsE7XnhmNpZSr3CcATV8Qs7MO+vTTs+3DYCmJNwBFqBP19NTaOakhnbrZN1/kJcwMgnQ5epPE3MYxnbxlWtUptuFo+hTbKNCa8v458WS14uEp7VlqSlSCJ5MKhnVvjeOKjVKUHkPQxqVRF8apL03/OHda406QavNH8j7WjeyxvsQ3aksOXQBedwlipQgU6SfUVx8qiuODTNT6AvTweUqUQpbHpbvjYy5wTu5Y711d7aHFnSidVnQkZ64HNouPlIHoSwX7Yngn850DeZds8rDFATvZAFaG7NCwkHmuYZu+Bnzxwb4hLKwrGWl8Q/fEGdDlw/+u1Me67GKazEJobK2xUeP2zf2EI3Mx7fpfkc4NykpQiYce9AfUxibinUIktVAJ0UKBBwE+ugsCQhqDO2JlemwdoX1E5eY/c5A8yqoWfZ7pNBNAmPtzlEwHN+HTUibC+bdXGkXu32mVM2HU8TfBPOuoLWmj3iXpOUVTDSZudcmILwtY2WUetSi9IP9MraZKu4Y9OS5end2SAtJ2FoD+2ZWfPklU9G2Olhs8Wp1dZdRQ0pwrI55x4VvcqJsX5in9DgcyO6+54HEA/eNlO5lMAVXBrCck8+7cN1H6q9fgAd79wP0gqipI81iNvA3SdkTyd9GUfS+ZhlP5K2RUENEdeQlIRa7fGWOChgrOZ6Zz8SDP6ZpHIkgVkljplD1Ct8LVHIazVLWwPSdPfdvzxcDIDgm97aW8xcv85Y0aK3AAKNqP9jOxrt4olvWuZZvA/2BmDYKzQMlJcYGsohtZ0MJUsLzpki7gk5/gg2FznxwVUKfVvAa25iLoiTomNy5cGy3nmGGD2jBfJ/Ntv4YOJ6j/YsxsEtRNWJjhjFYtjy+09EzlZKLcoV+aJStTt6Tza42Z8O+kj2HDqlcIoZtnUdDGe/IsP2TFkPb4+9VY7kp/XkwQoc9SYv/mEaE=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: helm-values
      namespace: argocd

