apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: helm-values
  namespace: argocd
spec:
  encryptedData:
    endpoint.yaml: AgC1FJMO6D4WufCIdpjf01gsdH41ISLnDGHC9aUvYciMu8BUYaSQjTPy9CsPJfmAozlZBbjm7kD1iRoIjCufHnsf1n2xzpEY6ozVO1JgxXmjKzv/I7tIL8SEaVvpfRhCMoUXRMjZ3ZosYGPCLI076ogSqb1UEsEycjxMKsGP3LkVBgikk9koh0+UCk0PmQw/ZwYzqPvztR0lhxYDTvXTxcovbuc+Lipg1cjtcWpTRicXo43ajcvfNSULH9+Rq4LgVpI4ak+/2KBTFsQqFfai6+XrB/Yllpcsiv9BSU5O9EIQipb17jYFlkJr7dTc92Wt1l72hRdTluOYUdl3/3bMItzy17/5RXJJmJchZTvx6uzrXhO//hIuDPH0e88MHz9W8NKrmHLhU9lXoaByaQ7I9EVdUDsszvItNa6j6qUvgTpT/wPgw8ECOl+VzY92uFxMwTVAdcMjGqXZQgVv17x6GyDJTXUtQ+fR75VSPG6d4D19YuRj8PlnXg7nLkRty0nqnp0vQ+vINgcIQradCRk4gdySt/5iZh7OVnTE4KXq2QJgdxxdhW/GWrojld6/mNG+rx/VQ3fSkozHYEGjpxVrQzf72xEXkLMcubzfBOc/BYSwk7y4ufpVwTqkjIGBplaHV2VqXjZtc3Yc+NjEetSrLgEnQpjJ5SX3CYnf1gYHwz5zFktvyDEJyN3v85j8/lXZL/G8AQ0Z2CIhSAhC0Nzz1s5iRYNcDDxLmXtdxdG8wU4kbliGg6rjuCCVbfbCGhGKabhD4BfI97KYzI9p0CcraM2QC6ZulL1oslzDc1uktYJK/QmODkn5m6JbmR+/tKIUT+qmLqBBLTh1WbejKOYF6b4MpSU3D0EuWeSD5Xh3dc6rGykCFgo03euhafmvik7DBRDGbkfLMWdK1mbJ940tCULDFoPA38GrnsO9IZ5w2Cxh7zzPyRqfl+XEAjuznEOEU6fanYC/PexJvE5uKKFqsiPa4C3BMUKRxVESPhRdODA=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: helm-values
      namespace: argocd

