apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-manager
  namespace: openshift-gitops
spec:
  destination:
    namespace: argocd       
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: manifest/argocd/apps/argocd-helm/overlays
    repoURL: https://github.com/StinkyBenji/hands-on-openshift-gitops
    targetRevision: master