apiVersion: v1
kind: ConfigMap
metadata:
  name: calert-config
  namespace: argocd
data:
  calert-config.toml: | 
    [app]
    address = "0.0.0.0:8080"
    server_timeout = "60s" # Server timeout for HTTP requests.
    enable_request_logs = true # Whether to log incoming HTTP requests or not.
    log = "info"

    [providers.safe_space]
    type = "google_chat"
    max_idle_conns =  50
    timeout = "30s"
    template = "static/message.tmpl"
    thread_ttl = "12h"
    dry_run = false
