apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertmanager
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: manifest/config/alertmanager/overlays
    repoURL: https://github.com/StinkyBenji/hands-on-openshift-gitops
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false