apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base
  - ../../manifest/argocd/argocd-notifications/overlays
  - ../../manifest/hashicorp-vault/base
  
patchesJson6902:
  - target:
      kind: ArgoCD
      name: openshift-gitops
      version: v1alpha1
      group: argoproj.io
    path: argocd.yaml

resources:
  - vault-namespace.yaml
  - vault-plugin-sa.yaml
  