apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  project: cluster-config
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 4.8.2
    helm:
      releaseName: custom-argo
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
