apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-config-manager
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: gitops-config
  source:
    path: openshift-gitops-operator/overlays
    repoURL: https://github.com/StinkyBenji/hands-on-openshift-gitops
    targetRevision: main
