apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-manager
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops 
    server: 'https://kubernetes.default.svc'         
  project: gitops-config
  source:
    repoURL: 'https://github.com/StinkyBenji/hands-on-openshift-gitops'
    path: manifest/argocd/vplugin-secrets/notifications-secret/overlays
    targetRevision: main
    plugin:
      name: argocd-vault-plugin
      env:
        - name: AVP_K8S_ROLE
          value: vplugin
        - name: AVP_TYPE
          value: vault
        - name: AVP_VAULT_ADDR
          value: 'http://vault-server.vault.srv.cluster.local:8200'
        - name: AVP_AUTH_TYPE
          value: k8s

